spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=backflix_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8085
  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true        
    properties:
      hibernate:
        format_sql: true 
        dialect: org.hibernate.dialect.SQLServerDialect
