spring:
  datasource:
    url: jdbc:h2:mem:backflixdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update    # cria/atualiza tabelas automaticamente
    show-sql: true        # mostra SQL no console
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true       # habilita o console web
      path: /h2-console   # caminho de acesso no navegador
